function misspecification
    addpath(genpath('../external'));
    addpath(genpath('../external/lib/matlab/blp/m'));
    load ../external/data/blp_estimation;
    load ../output/transp_identification_blp;
    load ../temp/markup_iv_sensitivity.mat;
    load ../temp/excluded_instrument_standard_deviations.mat;

    baseline_est = est;

    % Load data
    data = BlpData('blp_1999_data.csv', 'meanincome.csv', 'sdincome.csv');
    data = data.LoadUnobservablesFromEstimate(baseline_est);

    demand_iv_var = data.GetArray(baseline_est.model.demand_iv_varlist);
    supply_iv_var = data.GetArray(baseline_est.model.supply_iv_varlist);
    z             = blkdiag(demand_iv_var, supply_iv_var);

    % I. Get baseline estimates and point estimates for misspecification.
    % Get baseline parameters used in calculating perturbations
    k_xi                = baseline_est.GetWTPDerivative(data);
    [avg_price, avg_mc] = baseline_est.GetAvgPriceMC(data);

    % Calculate baseline avg markup
    baseline_markup = baseline_est.GetMeanMarkup(data);

    % Other parameters
    M_same  = data.GetCarsSameFirm();
    M_rival = data.GetCarsRivalFirm();
    n       = baseline_est.nmodels;

    % Create perturb_scaling.tsv file
    delta          = 0.01;
    demand_perturb =  delta .* avg_price ./ k_xi;
    supply_perturb = -delta .* avg_price ./ avg_mc;
    write_text_table([abs(demand_perturb); abs(supply_perturb)], ...
                     '../output/perturb_scaling.tsv', ...
                     {'demand', 'supply'}, {''}, '', 12);

    % For approximate sensitivity
    [supply_same_bias, supply_rival_bias, demand_same_bias, demand_rival_bias] = ...
            run_all_postests(blp1995.m_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, data);

    % For sample sensitivity
    [supply_same_bias_sample, supply_rival_bias_sample, demand_same_bias_sample, demand_rival_bias_sample] = ...
            run_all_postests(blp1995.m_sample_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, data);

    % II. Bias Estimation Bootstrap
    numbootstrap = 70;
    load '../external/data/blp_bootstrap_samples.mat'
    load '../external/data/bootstrap_estimates.mat'
    load '../external/data/bootstrap_std_sen.mat'
    load '../external/data/bootstrap_std_sample_sen.mat'

    % Define blank templates for bootstrap
    bootstrap_markup                      = zeros(numbootstrap, 1);
    bootstrap_markup_supply_same_bias     = zeros(numbootstrap, 1);
    bootstrap_markup_supply_rival_bias    = zeros(numbootstrap, 1);
    bootstrap_markup_demand_same_bias     = zeros(numbootstrap, 1);
    bootstrap_markup_demand_rival_bias    = zeros(numbootstrap, 1);

    bootstrap_markup_supply_same_bias_sample     = zeros(numbootstrap, 1);
    bootstrap_markup_supply_rival_bias_sample    = zeros(numbootstrap, 1);
    bootstrap_markup_demand_same_bias_sample     = zeros(numbootstrap, 1);
    bootstrap_markup_demand_rival_bias_sample    = zeros(numbootstrap, 1);

    for i = 1:numbootstrap
        disp(sprintf('Bootstrapping routine at iteration %d', i))

        boot_data          = bootsample_cell{i, 1};
        sensitivity        = squeeze(bootstrap_sens(i, :, :));
        sample_sensitivity = squeeze(bootstrap_sample_sens(i, :, :));
        boot_est           = bootstrap_estimates{i, 1};

        demand_iv_var = boot_data.GetArray(boot_est.model.demand_iv_varlist);
        supply_iv_var = boot_data.GetArray(boot_est.model.supply_iv_varlist);
        z = blkdiag(demand_iv_var, supply_iv_var);

        % Get markup sensitivity
        m_fun_param2         = @(param)bootstrap_estimates{i, 1}.GetMeanMarkup(boot_data, param);
        mjacobian_param      = NumJacob(m_fun_param2, bootstrap_estimates{i, 1}.param, 10^-4);
        mjacobian_beta       = zeros(1, length(bootstrap_estimates{i, 1}.beta));
        mjacobian            = [mjacobian_param, mjacobian_beta];

        [markup_sensitivity]        = get_counterfactual_sensitivity(sensitivity,        mjacobian);
        [markup_sample_sensitivity] = get_counterfactual_sensitivity(sample_sensitivity, mjacobian);

        % Other parameters for perturbations
        M_same  = boot_data.GetCarsSameFirm();
        M_rival = boot_data.GetCarsRivalFirm();
        n = boot_est.nmodels;

        % get baseline markup
        bootstrap_markup(i,1) = boot_est.GetMeanMarkup(boot_data);

        % get markup for approximate sensitivity
        [bootstrap_markup_supply_same_bias(i, 1), ...
        bootstrap_markup_supply_rival_bias(i, 1), ...
        bootstrap_markup_demand_same_bias(i, 1) , ...
        bootstrap_markup_demand_rival_bias(i, 1)] = ...
            run_all_postests(markup_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, boot_data);
        % get markup for sample sensitivity
        [bootstrap_markup_supply_same_bias_sample(i, 1), ...
        bootstrap_markup_supply_rival_bias_sample(i, 1), ...
        bootstrap_markup_demand_same_bias_sample(i, 1) , ...
        bootstrap_markup_demand_rival_bias_sample(i, 1)] = ...
            run_all_postests(markup_sample_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, boot_data);
    end

    % III. Write to table
    % % Approximate sensitivity
     bootstrap_table = get_markup_boot_table(bootstrap_markup, ...
                                         bootstrap_markup_supply_same_bias,   ...
                                         bootstrap_markup_supply_rival_bias, ...
                                         bootstrap_markup_demand_same_bias,   ...
                                         bootstrap_markup_demand_rival_bias, ...
                                         supply_same_bias, ...
                                         supply_rival_bias, ...
                                         demand_same_bias, ...
                                         demand_rival_bias, ...
                                         baseline_markup);

    bootstrap_table_rmse = [supply_same_bias; ...
                            supply_rival_bias; ...
                            demand_same_bias; ...
                            demand_rival_bias; ...
                            baseline_markup];

    write_text_table(bootstrap_table_rmse, '../output/bootstrap_misspecification_table.tsv', ...
                      {''; ''; ''; ''; ''}, '<tab:blp1995>', '', 12);

    % Sample sensitivity
     bootstrap_table_sample = get_markup_boot_table(bootstrap_markup, ...
                                             bootstrap_markup_supply_same_bias_sample,   ...
                                             bootstrap_markup_supply_rival_bias_sample, ...
                                             bootstrap_markup_demand_same_bias_sample,   ...
                                             bootstrap_markup_demand_rival_bias_sample, ...
                                             supply_same_bias_sample, ...
                                             supply_rival_bias_sample, ...
                                             demand_same_bias_sample, ...
                                             demand_rival_bias_sample, ...
                                             baseline_markup);

     names_bootstrap = {''; ''; ''; ''; ''; ''; ''; ''; ''; ''};
     write_text_table(bootstrap_table_sample, ...
                      '../output/bootstrap_misspecification_table_sample.tsv', ...
                      names_bootstrap, '<tab:blp1995_sample>', '', 12);

    % Global sensitivity from external
    load('../external/data/global_bootstrap_markup_supply_same_bias.mat');
    load('../external/data/global_bootstrap_markup_supply_rival_bias.mat');
    load('../external/data/global_bootstrap_markup_demand_same_bias.mat');
    load('../external/data/global_bootstrap_markup_demand_rival_bias.mat');
    global_bias = tblread('../external/data/blp1995_global_bias.tsv');
    global_supply_same_bias  = global_bias(1);
    global_supply_rival_bias = global_bias(2);
    global_demand_same_bias  = global_bias(3);
    global_demand_rival_bias = global_bias(4);

    bootstrap_table_global = get_markup_boot_table(bootstrap_markup, ...
                                            global_bootstrap_markup_supply_same_bias, ...
                                            global_bootstrap_markup_supply_rival_bias, ...
                                            global_bootstrap_markup_demand_same_bias, ...
                                            global_bootstrap_markup_demand_rival_bias, ...
                                            global_supply_same_bias, ...
                                            global_supply_rival_bias, ...
                                            global_demand_same_bias, ...
                                            global_demand_rival_bias, ...
                                            baseline_markup);

    % IV. Differencing global bias and first-order asymptotic bias
    % Diffing point estimates
    diff_supply_same   = supply_same_bias   - global_supply_same_bias;
    diff_supply_rival  = supply_rival_bias  - global_supply_rival_bias;
    diff_demand_same   = demand_same_bias   - global_demand_same_bias;
    diff_demand_rival  = demand_rival_bias  - global_demand_rival_bias;
    % Diffing the bootstrap vectors
    diff_boot_supply_same   = bootstrap_markup_supply_same_bias  - global_bootstrap_markup_supply_same_bias;
    diff_boot_supply_rival  = bootstrap_markup_supply_rival_bias - global_bootstrap_markup_supply_rival_bias;
    diff_boot_demand_same   = bootstrap_markup_demand_same_bias  - global_bootstrap_markup_demand_same_bias;
    diff_boot_demand_rival  = bootstrap_markup_demand_rival_bias - global_bootstrap_markup_demand_rival_bias;
    % Write to table
    diff_bootstrap_table = get_markup_boot_table(bootstrap_markup, ...
                                                 diff_boot_supply_same, ...
                                                 diff_boot_supply_rival, ...
                                                 diff_boot_demand_same, ...
                                                 diff_boot_demand_rival, ...
                                                 diff_supply_same, ...
                                                 diff_supply_rival, ...
                                                 diff_demand_same, ...
                                                 diff_demand_rival, ...
                                                 baseline_markup);

    write_text_table([bootstrap_table, bootstrap_table_global, diff_bootstrap_table], ...
                      '../output/bootstrap_misspecification_table_global.tsv', ...
                      names_bootstrap, {'<tab:blp1995_global>', '', ''}, '', 12)


    % V. Differencing global bias and local bias (sample version)
    % Diffing point estimates
    diff_supply_same   = supply_same_bias_sample   - global_supply_same_bias;
    diff_supply_rival  = supply_rival_bias_sample  - global_supply_rival_bias;
    diff_demand_same   = demand_same_bias_sample   - global_demand_same_bias;
    diff_demand_rival  = demand_rival_bias_sample  - global_demand_rival_bias;
    % Diffing the bootstrap vectors
    diff_boot_supply_same   = bootstrap_markup_supply_same_bias_sample  - global_bootstrap_markup_supply_same_bias;
    diff_boot_supply_rival  = bootstrap_markup_supply_rival_bias_sample - global_bootstrap_markup_supply_rival_bias;
    diff_boot_demand_same   = bootstrap_markup_demand_same_bias_sample  - global_bootstrap_markup_demand_same_bias;
    diff_boot_demand_rival  = bootstrap_markup_demand_rival_bias_sample - global_bootstrap_markup_demand_rival_bias;
    % Write to table
    diff_bootstrap_table = get_markup_boot_table(bootstrap_markup, ...
                                                 diff_boot_supply_same, ...
                                                 diff_boot_supply_rival, ...
                                                 diff_boot_demand_same, ...
                                                 diff_boot_demand_rival, ...
                                                 diff_supply_same, ...
                                                 diff_supply_rival, ...
                                                 diff_demand_same, ...
                                                 diff_demand_rival, ...
                                                 baseline_markup);

    write_text_table([bootstrap_table_sample, bootstrap_table_global, diff_bootstrap_table], ...
                      '../output/bootstrap_misspecification_table_global_sample.tsv', ...
                      names_bootstrap, {'<tab:blp1995_global_sample>', '', ''}, '', 12)

    % VI) Print IV sensitivity with the perturbation scaling
    excluded_instruments  = [6:13 20:31];
    excluded_names        = blp1995.momlist(excluded_instruments);
    excluded_sensitivity  = iv.sensitivity(excluded_instruments);
    scaled_iv_sensitivity = zeros(length(excluded_sensitivity), 1);

    for i = 1:length(excluded_instruments)
        moment_name = excluded_names{i};
        % Determine whether it is a supply or a demand moment
        moment_type = regexp(moment_name, '^[a-z]+', 'match');
        if strcmp(moment_type, 'demand')
            scaled_iv_sensitivity(i) = abs(demand_perturb) * excluded_sensitivity(i);
        elseif strcmp(moment_type, 'supply')
            scaled_iv_sensitivity(i) = abs(supply_perturb) * excluded_sensitivity(i);
        end
    end
    write_text_table(scaled_iv_sensitivity, ...
                     '../output/markup_sen_own_units.tsv', ...
                     excluded_names, 'markup', '', 12);

    % Now scale by standard deviations
    scaled_iv_sensitivity = scaled_iv_sensitivity ./ std_excluded;
    write_text_table(scaled_iv_sensitivity, ...
                     '../output/markup_sen_scaled.tsv', ...
                     excluded_names, 'markup', '', 12);

    exit
end


function [supply_same_bias, supply_rival_bias, demand_same_bias, demand_rival_bias] = ...
            run_all_postests(markup_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, data)

    supply_same_bias  = post_estimation_markup_bias('supply', 'same',  ...
                        markup_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, data);
    supply_rival_bias = post_estimation_markup_bias('supply', 'rival', ...
                        markup_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, data);
    demand_same_bias  = post_estimation_markup_bias('demand', 'same',  ...
                        markup_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, data);
    demand_rival_bias = post_estimation_markup_bias('demand', 'rival', ...
                        markup_sensitivity, avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, data);

end

function mean_markup_bias = post_estimation_markup_bias(demand_supply, same_rival, markup_sensitivity, ...
                                                        avg_price, avg_mc, k_xi, delta, n, M_same, M_rival, z, data)

    misspec_perturb = BlpGetMisspec(demand_supply, same_rival, delta,...
                                    avg_price, avg_mc, k_xi, ...
                                    M_same, M_rival);

    L = (z' * misspec_perturb) ./ n;
    mean_markup_bias = markup_sensitivity * L;

end

function boottable = get_markup_boot_table(bootstrap_markup, ...
                                            bootstrap_markup_supply_same_bias,   ...
                                            bootstrap_markup_supply_rival_bias, ...
                                            bootstrap_markup_demand_same_bias,   ...
                                            bootstrap_markup_demand_rival_bias, ...
                                            supply_same_bias, ...
                                            supply_rival_bias, ...
                                            demand_same_bias, ...
                                            demand_rival_bias, ...
                                            baseline_markup)

    se_bootstrap_markup                          = std(bootstrap_markup);
    se_bootstrap_markup_supply_same_bias         = std(bootstrap_markup_supply_same_bias);
    se_bootstrap_markup_supply_rival_bias        = std(bootstrap_markup_supply_rival_bias);
    se_bootstrap_markup_demand_same_bias         = std(bootstrap_markup_demand_same_bias);
    se_bootstrap_markup_demand_rival_bias        = std(bootstrap_markup_demand_rival_bias);


    boottable = [supply_same_bias;   se_bootstrap_markup_supply_same_bias; ...
                 supply_rival_bias;  se_bootstrap_markup_supply_rival_bias; ...
                 demand_same_bias;   se_bootstrap_markup_demand_same_bias; ...
                 demand_rival_bias;  se_bootstrap_markup_demand_rival_bias; ...
                 baseline_markup;    se_bootstrap_markup];
end
